version: '3.9'

services:
  frontend:
    build: ./shop4pi-tests
    ports:
      - "80:80"
    environment:
      - REACT_APP_API_URL=http://backend:5000
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongo:27017/shop4pi
      - MONGODB_USERNAME=admin
      - MONGODB_PASSWORD=password
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    ports:
      - "27027:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=shop4pi
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
